### PR TITLE
Extractor for exams supervision

### LINKED ISSUE #111: One-click url for Outlook is broken. Again :upside_down_face:
Microsoft being Microsoft I guess :slightly_smiling_face: 

So it seems Outlook does not like the timezone offsets in the ISO date formats, i.e. `2022-03-26T00:00:00-04:00`. Although that is standardised and worked previously. From my experiments, converting to UTC should do the trick

### PR DESCRIPTION
**Pull request by fabiodrg**
# Changes

- Create a class for representing a calendar event, `CalEvent` (#107).
  - Ensure a consistent object across extractors and distinct modules.
  - Events can be set as recurrent and have the recurrence period built-in.
  - It calculates the start/end date-times according to the recurrence and also generates the recurrence rule object (#110).
- Add a more specialised extractor class, `EventExtractor`, to distinguish between generic extractors and extractors that create calendar events.
  - The `EventExtractor` supports the format-strings for title and description, customisable via options UI (#107).
  - The extractor should create instances of `CalEvent` with the formatted strings to separate the semantics of extractors and events. Generating UI only needs the events objects with this approach
- Create an utility class for generating URLs for the 'one-click' feature
  - Replaces the old global functions API in `calendar.js`
  - Works with the new  `CalEvent` class
  - Fixes #111 
- Refactor the utility functions that generate the modal UI for downloading events and the dropdowns for adding singular events to Google/Microsoft/Yahoo calendars.
  - Supports `CalEvent` class
  - The custom recurrence rules now work for the ICS file, as well as 'one-click' events in the dropdowns 
- Add extractor for exams supervisions

# Preview
image
image
image

### CODE REVIEW

File: src/js/extractors/supervisions.js [hunk 1]
```diff
@@ -0,0 +1,166 @@
...
+        let [acronym, name] = course.split("-").map((s) => s.trim());
+        name = name.replace(/ \(.*\)/, ""); // remove the course identifier, e.g. L.EIC015
+        const url = $td[2].querySelector("a").href;
+
+        // Parse rooms, if available
+        const location = $td[3].innerText || null;
+
+        return {
+            startTime: new Date(`${date} ${startTime}`),
+            endTime: new Date(`${date} ${endTime}`),
```
Comment (msramalho) [inline src/js/extractors/supervisions.js:157]: cool hack

File: src/js/utils/dropdown.js [hunk 2]
```diff
@@ -111,4 +119,168 @@ window.onclick = function (event) {
...
+                    "icons/calendar.png"
+                )}">
+                Others (.ics)
+            </a>
+        </div>
+    </div>`);
+
+    // add click action for the ICS download button
+    $dropdown.querySelector(".donwloadSingleIcs").addEventListener("click", (e) => {
+        const cal = ics("sigtools"); //creat ics instance
```
Comment (msramalho) [inline src/js/utils/dropdown.js:187]:
```suggestion
        const cal = ics("sigtools"); //create ics instance
```

File: src/js/utils/dropdown.js [hunk 3]
```diff
@@ -111,4 +119,168 @@ window.onclick = function (event) {
...
+        cal.addEvent(event.title, event.description, event.location, event.start, event.end, event.recurRule);
```
Comment (msramalho) [inline src/js/utils/dropdown.js:188]: I wonder if we can eventually refactor addEvent to receive an object instead of having to be this explicit, perhaps that could make the communication a bit less coupled, but not a priority for this PR
